# Generated by Django 3.2.5 on 2022-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220609_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_data_entry_user',
            new_name='is_data_entry',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_student', 'is_student'), ('is_staff', 'is_staff')], default='0', max_length=20),
        ),
    ]
