# Generated by Django 3.2.5 on 2022-06-09 06:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220609_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=accounts.models.Profile.upload_design_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_student', 'is_student'), ('is_staff', 'is_staff'), ('is_admin', 'is_admin')], default='0', max_length=20),
        ),
    ]
