# Generated by Django 3.2.5 on 2022-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220609_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('is_admin', 'is_admin'), ('is_student', 'is_student'), ('is_staff', 'is_staff')], default='0', max_length=20),
        ),
    ]
