# Generated by Django 3.2.5 on 2022-06-10 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=1234567890, max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
