# Generated by Django 3.2.5 on 2022-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_answers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Match_the_following', 'Match_the_following'), ('MCQ', 'MCQ'), ('Fill_in_the_blanks', 'Fill_in_the_blanks')], default='0', max_length=20),
        ),
    ]
