# Generated by Django 3.2.5 on 2022-06-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20220613_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Comprehension', 'Comprehension'), ('Knowledge', 'Knowledge'), ('Application', 'Application')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard'), ('Medium', 'Medium')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Match_the_following', 'Match_the_following'), ('Fill_in_the_blanks', 'Fill_in_the_blanks'), ('MCQ', 'MCQ')], default='0', max_length=20),
        ),
    ]
