# Generated by Django 3.2.5 on 2022-06-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_auto_20220614_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='option_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='option_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='option_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='option_d',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Knowledge', 'Knowledge'), ('Comprehension', 'Comprehension'), ('Application', 'Application')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Fill_in_the_blanks', 'Fill_in_the_blanks'), ('Match_the_following', 'Match_the_following')], default='0', max_length=20),
        ),
    ]
