# Generated by Django 3.2.5 on 2022-06-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_auto_20220614_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Application', 'Application'), ('Knowledge', 'Knowledge'), ('Comprehension', 'Comprehension')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Easy', 'Easy'), ('Medium', 'Medium')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Fill_in_the_blanks', 'Fill_in_the_blanks'), ('MCQ', 'MCQ'), ('Match_the_following', 'Match_the_following')], default='0', max_length=20),
        ),
    ]
