# Generated by Django 3.2.5 on 2022-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_auto_20220615_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Application', 'Application'), ('Comprehension', 'Comprehension'), ('Knowledge', 'Knowledge')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Fill_in_the_blanks', 'Fill_in_the_blanks'), ('Match_the_following', 'Match_the_following'), ('MCQ', 'MCQ')], default='0', max_length=20),
        ),
    ]
