# Generated by Django 3.2.5 on 2022-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20220615_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Comprehension', 'Comprehension'), ('Knowledge', 'Knowledge'), ('Application', 'Application')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Match_the_following', 'Match_the_following'), ('MCQ', 'MCQ'), ('Fill_in_the_blanks', 'Fill_in_the_blanks')], default='0', max_length=20),
        ),
    ]
